### ISSUE TITLE
Error While Compiling

### ISSUE THREAD

**Issue by razarehman56** [landofcoder/module-product-tags#49]
After compiling code following error is coming.
In ErrorHandler.php line 61:
                                                                               
  Warning: Declaration of Lof\ProductTags\Model\ResourceModel\Tag::_afterSave  
  ($tag) should be compatible with Magento\Framework\Model\ResourceModel\Db\A  
  bstractDb::_afterSave(Magento\Framework\Model\AbstractModel $object) in /va  
  r/www/html/rtlsol_magento2/app/code/Lof/ProductTags/Model/ResourceModel/Tag  
  .php on line 439

**Comment by landofcoder** [comment]
Dear,
Please update the module file with new commit at here: https://github.com/landofcoder/module-product-tags/pull/50/commits/82127e75678af343978a1fb74419e45c85ac355e
