### ISSUE TITLE
No ability to add tags to a product

### ISSUE THREAD

**Issue by teamsignprompt** [landofcoder/module-product-tags#51]
I have Magento version 2.3.5-p2 installed. I was able to successfully install the product tags extension from the master branch, after which I created a test tag.

However, there doesn't appear to be any way to attach a tag when adding/editing a product. There is nothing under Catalog > Products referring to tags that I have been able to find, after installing the extension.

**Comment by landofcoder** [comment]
Dear Mate,
At now the module just assign products for tag when edit tag on backend, and does not support choose tags when edit product item.
